---
- name: Hello World Playbook
  hosts: localhost  # Replace with the hostname or IP address of your target machine
  gather_facts: false

  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World!"
